document.addEventListener("DOMContentLoaded", function() {
    var submitButton = document.getElementById("submitBtn");
    var continentInfo = document.getElementById("continentInfo");

    submitButton.addEventListener("click", function() {
        var selectedContinent = document.getElementById("continents").value;
        var continentDescription = getContinentDescription(selectedContinent);
        continentInfo.innerHTML = continentDescription;
        continentInfo.style.display = "block";
    });
    window.addEventListener("scroll", function() {
        var footer = document.getElementById("footer");
        var distanceFromTop = footer.getBoundingClientRect().top;
        var windowHeight = window.innerHeight;
    
        // Check if the footer is in the viewport
        if (distanceFromTop < windowHeight) {
            footer.style.position = "fixed";
            footer.style.bottom = "0";
        } else {
            footer.style.position = "relative";
        }
    });
    

    function getContinentDescription(continent) {
        switch (continent) {
            case "North America":
               return "<div><strong style='margin: 10px auto; display: block; text-align: center;'>Sustainable Forest Management in North America</strong></div><div><img src='OIP.jpg' alt='' style='float:left;width:300px;height:300px;margin-right:10px;'></div><div><img src='forestimg.jpg' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p>The issue of forest shrinking in North America, particularly related to tree harvesting for wood fiber, has been widely discussed and misunderstood. Despite misconceptions perpetuated by anti-paper campaigns, paper products are inherently sustainable, recyclable, and manufactured with renewable energy sources.</p><p>To combat these misconceptions effectively, it's essential to rely on concrete data. The United Nations Food and Agriculture Organization's 2020 Forest Resources Assessment offers comprehensive insights into global forest trends, revealing a net increase in forest area in the United States and stable forest area in Canada since 1990.</p><p>This positive trend is largely attributed to sustainable forest management practices adopted by the North American paper and forest products industry, alongside stringent laws and regulations aimed at preserving forest resources. Despite challenges such as urban development and natural causes of deforestation, the implementation of sustainable forestry practices has played a significant role in maintaining and even expanding forests in North America.</p><p><a href='https://www.bing.com/ck/a?!&&p=66ecc30b5d4b7142JmltdHM9MTcwNzYwOTYwMCZpZ3VpZD0xYjY2ZGJiYi1hNTJlLTY1NmQtMDBkNC1jODU3YTQ3YzY0YjEmaW5zaWQ9NTI2MA&ptn=3&ver=2&hsh=3&fclid=1b66dbbb-a52e-656d-00d4-c857a47c64b1&psq=forests+in+north+america&u=a1aHR0cHM6Ly9lbi53aWtpcGVkaWEub3JnL3dpa2kvRm9yZXN0c19vZl90aGVfVW5pdGVkX1N0YXRlcw&ntb=1' target='_blank' style='margin: 10px auto; display: block; text-align: center;'>Know More</a></p></div>";
            case "South America":
                return "<div><strong style='margin: 10px auto; display: block; text-align: center;'>Combatting Forest Shrinking in South America</strong></div><div><img src='southamer.gif' alt='' style='float:left;width:300px;height:300px;margin-right:10px;'></div><div><img src='southamerica_forest.jpg' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p>The shrinking of forests in South America presents a critical environmental challenge with far-reaching implications. Rapid deforestation, primarily driven by agricultural expansion and logging, threatens the invaluable biodiversity of the Amazon rainforest and other vital ecosystems. This loss of habitat not only endangers countless plant and animal species but also contributes significantly to climate change by releasing stored carbon into the atmosphere.</p><p>The consequences of forest depletion in South America extend beyond local ecosystems, impacting global climate stability and regional weather patterns. Deforestation disrupts water cycles, increases the risk of natural disasters like floods and landslides, and exacerbates soil erosion. Such environmental disruptions pose significant risks to indigenous communities and wildlife while undermining the overall ecological balance of the region.</p><p>Addressing the challenge of forest shrinking in South America necessitates a multifaceted approach, including robust government policies, sustainable land management practices, and conservation efforts. Governments must enact stringent regulations to curb deforestation while promoting sustainable agriculture and alternative livelihoods for local communities. Additionally, investing in reforestation initiatives and protected area management is crucial for restoring degraded landscapes and fostering long-term resilience in South America's forests.</p><p><a href='https://www.bing.com/ck/a?!&&p=43bc0fbb6f58145fJmltdHM9MTcwNzYwOTYwMCZpZ3VpZD0xYjY2ZGJiYi1hNTJlLTY1NmQtMDBkNC1jODU3YTQ3YzY0YjEmaW5zaWQ9NTIyMg&ptn=3&ver=2&hsh=3&fclid=1b66dbbb-a52e-656d-00d4-c857a47c64b1&psq=forests+in+south+america&u=a1aHR0cHM6Ly93d3cuYnJpdGFubmljYS5jb20vcGxhY2UvU291dGgtQW1lcmljYS9Ucm9waWNhbC1hbmQtc3VidHJvcGljYWwtcmFpbmZvcmVzdHM&ntb=1' target='_blank' style='margin: 10px auto; display: block; text-align: center;'>Know More</a></p></div>";
            case "Europe":
                return "<div><strong style='margin: 10px auto; display: block; text-align: center;'>Sustainable Forest Management in Europe</strong></div><div><img src='europff.jpg' alt='' style='float:left;width:300px;height:300px;margin-right:10px;'></div><div><img src='eruope_forest.jpg' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p>In Europe, forest shrinking has been a topic of concern, albeit to a lesser extent compared to other regions. While Europe is known for its extensive forest cover, certain areas have experienced declines in forest area due to various factors such as urbanization, agricultural expansion, and natural disturbances like wildfires and pests. However, it's essential to note that Europe has also made significant strides in forest conservation and management.</p><p>Efforts to combat forest shrinking in Europe have been multifaceted, including initiatives to promote sustainable forestry practices, reforestation projects, and the establishment of protected areas. European countries have implemented strict regulations and policies aimed at preserving and expanding forest cover, recognizing the ecological, economic, and social importance of forests. Additionally, public awareness campaigns and community engagement have played vital roles in fostering a culture of forest conservation across the continent.</p><p>Despite ongoing challenges, Europe continues to prioritize the preservation of its forests and biodiversity. Through collaborative efforts between governments, organizations, and local communities, Europe aims to mitigate the impacts of forest shrinking while promoting sustainable land use practices.</p><p><a href='Despite ongoing challenges, Europe continues to prioritize the preservation of its forests and biodiversity. Through collaborative efforts between governments, organizations, and local communities, Europe aims to mitigate the impacts of forest shrinking while promoting sustainable land use practices.' target='_blank' style='margin: 10px auto; display: block; text-align: center;'>Know More</a></p></div>";
            case "Asia":
                return "<div><strong style='margin: 10px auto; display: block; text-align: center;'>Sustainable Forest Management in Asia</strong></div><div><img src='asiff.jpg' alt='' style='float:left;width:300px;height:300px;margin-right:10px;'></div><div><img src='asia_forest.jpg' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p>In recent years, Asia has faced significant challenges regarding forest preservation, with shrinking forest cover being a notable concern. Rapid urbanization, industrial expansion, agricultural development, and illegal logging have all contributed to the decline in Asia's forested areas. These activities have led to habitat loss, biodiversity depletion, and disruptions to ecosystems across the continent.</p><p>The consequences of forest shrinkage in Asia are far-reaching, impacting not only the environment but also human populations and economies. Deforestation threatens the livelihoods of indigenous communities dependent on forests for sustenance and cultural heritage. Furthermore, it exacerbates climate change by reducing carbon sequestration capacity and increasing greenhouse gas emissions, thus contributing to global warming.</p><p>Addressing the issue of forest shrinking in Asia requires concerted efforts at local, national, and international levels. Implementing sustainable land management practices, enforcing stricter regulations on logging and land conversion, promoting reforestation initiatives, and empowering local communities in forest conservation efforts are vital steps towards mitigating the impact of deforestation and preserving Asia's invaluable forest ecosystems for future generations.</p><p><a href='https://www.bing.com/ck/a?!&&p=ad9a735d1a4b7a4bJmltdHM9MTcwNzYwOTYwMCZpZ3VpZD0xYjY2ZGJiYi1hNTJlLTY1NmQtMDBkNC1jODU3YTQ3YzY0YjEmaW5zaWQ9NTIzMw&ptn=3&ver=2&hsh=3&fclid=1b66dbbb-a52e-656d-00d4-c857a47c64b1&psq=forests+in+asia&u=a1aHR0cHM6Ly93d3cuYnJpdGFubmljYS5jb20vcGxhY2UvQXNpYS9QbGFudC1saWZl&ntb=1' target='_blank' style='margin: 10px auto; display: block; text-align: center;'>Know More</a></p></div>";
            case "Africa":
                return "<div><strong style='margin: 10px auto; display: block; text-align: center;'>Combatting Forest Shrinking in Africa</strong></div><div><img src='affr.jpg' alt='' style='float:left;width:300px;height:300px;margin-right:10px;'></div><div><img src='african_forest.jpg' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p>In recent decades, Africa has faced significant challenges related to forest shrinking, driven by various factors including deforestation, land degradation, and climate change. The continent's forests, vital for biodiversity, carbon sequestration, and local livelihoods, have experienced alarming rates of deforestation due to agricultural expansion, logging, and infrastructure development. Additionally, unsustainable land-use practices and population growth exacerbate the pressure on Africa's forests, leading to their gradual decline.</p><p>Despite these challenges, concerted efforts are underway to address forest shrinking in Africa. Governments, non-governmental organizations, and international initiatives are implementing measures to promote sustainable forest management, conservation, and reforestation. Community-based approaches, along with the engagement of indigenous peoples and local communities, play a crucial role in preserving and restoring Africa's forests.</p><p>Furthermore, initiatives focusing on alternative livelihoods, eco-tourism, and sustainable resource management contribute to mitigating forest loss while supporting local communities.</p><p><a href='https://www.bing.com/ck/a?!&&p=3ad42b00d5d4747dJmltdHM9MTcwNzYwOTYwMCZpZ3VpZD0xYjY2ZGJiYi1hNTJlLTY1NmQtMDBkNC1jODU3YTQ3YzY0YjEmaW5zaWQ9NTMzNg&ptn=3&ver=2&hsh=3&fclid=1b66dbbb-a52e-656d-00d4-c857a47c64b1&psq=forests+in+africa&u=a1aHR0cHM6Ly93d3cuYWZyaWNhbmZvcmVzdHMub3JnLw&ntb=1' target='_blank' style='margin: 10px auto; display: block; text-align: center;'>Know More</a></p></div>";
            case "Australia":
                return "<div><strong style='margin: 10px auto; display: block; text-align: center;'>Sustainable Forest Management in Australia</strong></div><div><img src='austfor.jpg' alt='' style='float:left;width:300px;height:300px;margin-right:10px;'></div><div><img src='austraila_forest.jpeg' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p>In recent years, Australia has faced significant challenges related to forest shrinking, primarily due to factors such as deforestation, wildfires, and land clearing for agricultural purposes. These activities have led to the loss of valuable forest ecosystems and habitats for numerous plant and animal species, exacerbating environmental degradation and biodiversity loss.</p><p>The impacts of forest shrinking in Australia are profound and multifaceted. Not only does it threaten the survival of indigenous flora and fauna, but it also contributes to soil erosion, loss of water resources, and increased greenhouse gas emissions. Additionally, the decline in forest cover diminishes the natural resilience of ecosystems, making them more susceptible to the adverse effects of climate change, such as extreme weather events and habitat fragmentation.</p><p>Addressing the issue of forest shrinking in Australia requires a multifaceted approach that integrates sustainable land management practices, conservation efforts, and policy interventions. By promoting reforestation, implementing strict regulations on land use, and engaging local communities in forest conservation initiatives, Australia can work towards mitigating the detrimental effects of forest shrinking and fostering the restoration of vital ecosystems for future generations.</p><p><a href='https://www.bing.com/ck/a?!&&p=8aa7daca585210fcJmltdHM9MTcwNzYwOTYwMCZpZ3VpZD0xYjY2ZGJiYi1hNTJlLTY1NmQtMDBkNC1jODU3YTQ3YzY0YjEmaW5zaWQ9NTI5Mw&ptn=3&ver=2&hsh=3&fclid=1b66dbbb-a52e-656d-00d4-c857a47c64b1&psq=forests+in+AUSTRALIA&u=a1aHR0cHM6Ly93d3cuYWdyaWN1bHR1cmUuZ292LmF1L2FiYXJlcy9mb3Jlc3RzYXVzdHJhbGlhL2F1c3RyYWxpYXMtZm9yZXN0cw&ntb=1' target='_blank' style='margin: 10px auto; display: block; text-align: center;'>Know More</a></p></div>";
            case "Antarctica":
                return "<div><strong style='margin: 10px auto; display: block; text-align: center;'>Sustainable Forest Management in Antarctica</strong></div><div><img src='anticafr.png' alt='' style='float:left;width:300px;height:300px;margin-right:10px;'></div><div><img src='antarctica_forest.jpg' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p>The issue of forest shrinking in Antarctica is a complex one, primarily due to the continent's extreme climate and the absence of significant human habitation and industrial activity. While Antarctica is home to some vegetation, including mosses, lichens, and algae, it lacks the extensive forests found on other continents. Therefore, the concept of forest shrinking in the traditional sense does not apply to Antarctica.</p><p>However, the continent faces other environmental challenges, such as the impact of climate change on its fragile ecosystems. Rising temperatures, melting ice shelves, and changing precipitation patterns can affect the distribution and abundance of plant life, including the limited vegetation found in Antarctica. Additionally, human activities, such as scientific research and tourism, can have localized impacts on Antarctic ecosystems, although these are typically regulated to minimize environmental harm.</p><p> Climate change and human activities can still impact the delicate balance of Antarctic ecosystems, underscoring the need for continued research, conservation efforts, and international cooperation to preserve this unique and ecologically important region.</p><p><a href=' https://www.bbc.com/news/science-environment-12378934' target='_blank' style='margin: 10px auto; display: block; text-align: center;'>Know More</a></p></div>";
            default:
                return "<p>No information available for this continent.</p>";
        }
    }
});
